# Update files
# Use wget "-r" to overwrite current file

update:
	wget -r https://raw.githubusercontent.com/nodeca/js-yaml/master/dist/js-yaml.min.js

# Use validator package, https://github.com/validatorjs/validator.js
#	wget -r https://unpkg.com/validator@latest/validator.min.js
